# Generated by Django 4.2.25 on 2026-05-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0113_epic_update'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='initiative',
            name='initiative_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='initiative',
            name='initiative_archived_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='issue_parent_idx',
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='issue_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='issue_project_type_idx',
        ),
        migrations.AddField(
            model_name='customproperty',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='epicupdate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='initiativeepic',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='issuecustompropertyvalue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='customproperty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='customproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AlterField(
            model_name='initiativeepic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='initiativeepic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AlterField(
            model_name='issuecustompropertyvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='issuecustompropertyvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
    ]
